name: Check for new reports

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    environment: checker script env

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-python@main
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
    
      - run: uv sync --locked --all-extras --dev

      - name: Run check script
        env:
          SLACK_HOOK_STATE_ELECTIONS: ${{ secrets.SLACK_HOOK_STATE_ELECTIONS }}
        run: uv run python check.py